### ISSUE TITLE
CRL Check is missing

### ISSUE THREAD

**Issue by honzirek** [gematik/ref-GemLibPki#17]
Hello,

I would like to ask why the CRL Check (TUC_PKI_021) is missing in this reference implementation. According to the [gemSpec_PKI] it should be part of the Certificate Validation (TUC_PKI_018). 

Thank you.

**Comment by RStaeber** [comment]
The CRL is only used by the connector (Netzkonnektor) to check certificates.
The relevant certificate types are C.VPN.VPNK and C.VPN.VPNK-SIS.
Since the use of the CRL only affects a few use cases, it was decided not to implement the TUC_PKI_021.
