### ISSUE TITLE
Extend CertificateProfile to allow verify SSL Server certificates

### ISSUE THREAD

**Issue by fb-wl** [gematik/ref-GemLibPki#3]
Hello all,

is it possible to open the API in order to support the TUC_PKI_018 verification of further certificate profiles? For example the SSL server certificate profile (oid_fd_tls_s / 1.2.276.0.76.4.169) is missing. Currently (v1.0.0.0) the related policy 1.2.276.0.76.4.169 is already defined as `CertificateType`, but there is no corresponding `CertificateProfile`. 

Perhaps there is the possibility of replacing the practical but very restrictive mapping of the certificates profiles via Java-enums with a more open data structure, e.g. Java-interfaces? 

If you are interested and if desired, I could make a corresponding pull request.

Best wishes,
Frank

**Comment by mjechow** [comment]
Hi Frank,

we plan a new release very soon. I am implementing oid_fd_tls_s  right now. We will discuss your suggestion to switch to interfaces internally.

Greetings, Mirko
